name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.3.8
          - 2.5.8
          - 2.6.8
          - 2.7.6
          - 3.0.4
          - 3.1.2
          - 3.2.0
    steps:
    - uses: zendesk/checkout@v3
    - name: Set up Ruby
      uses: zendesk/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Test ${{ matrix.ruby-version }}
      run: |
        bundle install
        bundle exec rspec spec
